// src/app/layout.tsx
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  // No useEffect or ClientSideEffect required here

  return (
    <html lang='en'>
      <head>
        {/* Place any head tags, like meta, title, link or script tags, here */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
